import { Hit } from "./dataType";

export const testData: Hit[] = [
  {
    index: 1,
    name: "抹茶 100g 2個セット 鹿児島県産抹茶100%",
    description:
      "抹茶の原料「碾茶」は、煎茶と同じお茶の木から作られていますが、栽培の際に覆いをかけて大切に育てられます。<br>日光を遮られたお茶の葉は、渋み成分のタンニンが少なく、甘み成分のテアニンが多くなり、抹茶に適した高級茶葉になります。<br><br>",
    headLine: "鹿児島県産100%の抹茶誕生",
    url: "https://store.shopping.yahoo.co.jp/cin/10000040.html",
    inStock: true,
    code: "cin_10000040",
    condition: "new",
    imageId: "cin_10000040",
    image: {
      small: "https://item-shopping.c.yimg.jp/i/c/cin_10000040",
      medium: "https://item-shopping.c.yimg.jp/i/g/cin_10000040",
    },
    review: {
      count: 171,
      url: "https://shopping.yahoo.co.jp/review/item/list?store_id=cin&page_key=10000040",
      rate: 4.73,
    },
    affiliateRate: 1,
    price: 2000,
    premiumPrice: 1000,
    premiumPriceStatus: true,
    premiumDiscountRate: 50,
    premiumDiscountType: "normal",
    priceLabel: {
      taxable: true,
      defaultPrice: 2000,
      discountedPrice: null,
      fixedPrice: null,
      premiumPrice: 1000,
      periodStart: null,
      periodEnd: null,
    },
    point: {
      amount: 0,
      times: 0,
      bonusAmount: 36,
      bonusTimes: 2,
      premiumAmount: 0,
      premiumTimes: 0,
      premiumBonusAmount: 18,
      premiumBonusTimes: 2,
    },
    shipping: {
      code: 2,
      name: "送料無料",
    },
    genreCategory: {
      id: 17362,
      name: "抹茶",
      depth: 4,
    },
    parentGenreCategories: [
      {
        id: 2498,
        depth: 1,
        name: "食品",
      },
      {
        id: 2499,
        depth: 2,
        name: "ドリンク、水、お酒",
      },
      {
        id: 1399,
        depth: 3,
        name: "緑茶、日本茶",
      },
    ],
    brand: {
      id: 38074,
      name: "ブランド登録なし",
    },
    parentBrands: [
      {
        id: 1,
        name: "ブランド",
      },
    ],
    janCode: "",
    payment: "8192 16384 1024 4096 16 1 64",
    releaseDate: null,
    seller: {
      sellerId: "cin",
      name: "知覧一番山農園",
      url: "https://store.shopping.yahoo.co.jp/cin/",
      isBestSeller: false,
      review: {
        rate: 4.73,
        count: 55,
      },
      imageId: "cin_1",
    },
    delivery: {
      deadLine: null,
      day: null,
      area: "",
    },
  },
  {
    index: 2,
    name: "業務用サイズ 京都産 宇治抹茶 500g 大袋タイプ 日本茶 緑茶 パウダー 粉末 メール便 送料無料",
    description:
      "500gの業務用サイズ。<br>日常に多く使う個人の方にも。<br><br>名称：抹茶<br>内容量：500g<br>原材料名：緑茶(京都)<br>保存方法：直射日光・高温多湿の場所を避け、冷暗所にて保存して下さい。<br>配送区分<br>ゆうメール：全国送料無料　 代金引換×　他商品一部同梱×<br>宅配便  ：送料600円(税別)　代金引換○　他商品同梱○<br>(北海道・沖縄・離島除く)<br>製造者：株式会社高村園<br>広島県広島市安佐北区口田南1-25-27<br>TEL 082-845-8878<br><br>※原材料の緑茶の表示につきまして<br>抹茶の原料は碾茶ですが、碾茶の原料も緑茶となります。(煎茶やほうじ茶なども緑茶もしくは茶と表示)<br>この時、名称を抹茶とできるのは碾茶100%の場合です。本商品は碾茶100%から作られた抹茶となります。<br><br>※クリックポスト・ゆうパケットのため、手渡しではなく、ポスト投函となりますので、何卒ご了承くださいますよう、お願い致します。<br>追跡番号の発行がされます。ポストにお荷物が入らない場合、不在票が投函されますので、ご確認ください。",
    headLine: "チャック付袋 稽古用 料理用 お菓子作り 送料無料 日本茶 緑茶",
    url: "https://store.shopping.yahoo.co.jp/ichinoen/kyoto-uji500.html",
    inStock: true,
    code: "ichinoen_kyoto-uji500",
    condition: "new",
    imageId: "ichinoen_kyoto-uji500",
    image: {
      small: "https://item-shopping.c.yimg.jp/i/c/ichinoen_kyoto-uji500",
      medium: "https://item-shopping.c.yimg.jp/i/g/ichinoen_kyoto-uji500",
    },
    review: {
      count: 186,
      url: "https://shopping.yahoo.co.jp/review/item/list?store_id=ichinoen&page_key=kyoto-uji500",
      rate: 4.72,
    },
    affiliateRate: 1,
    price: 2160,
    premiumPrice: 2160,
    premiumPriceStatus: false,
    premiumDiscountRate: null,
    premiumDiscountType: null,
    priceLabel: {
      taxable: true,
      defaultPrice: 2160,
      discountedPrice: null,
      fixedPrice: null,
      premiumPrice: null,
      periodStart: null,
      periodEnd: null,
    },
    point: {
      amount: 0,
      times: 0,
      bonusAmount: 20,
      bonusTimes: 1,
      premiumAmount: 0,
      premiumTimes: 0,
      premiumBonusAmount: 20,
      premiumBonusTimes: 1,
    },
    shipping: {
      code: 2,
      name: "送料無料",
    },
    genreCategory: {
      id: 17362,
      name: "抹茶",
      depth: 4,
    },
    parentGenreCategories: [
      {
        id: 2498,
        depth: 1,
        name: "食品",
      },
      {
        id: 2499,
        depth: 2,
        name: "ドリンク、水、お酒",
      },
      {
        id: 1399,
        depth: 3,
        name: "緑茶、日本茶",
      },
    ],
    brand: {
      id: null,
      name: "",
    },
    parentBrands: [],
    janCode: "",
    payment: "1024 8192 1 8 128 512 16 64 256 4 4096 16384 2",
    releaseDate: null,
    seller: {
      sellerId: "ichinoen",
      name: "一の縁",
      url: "https://store.shopping.yahoo.co.jp/ichinoen/",
      isBestSeller: false,
      review: {
        rate: 4.77,
        count: 1062,
      },
      imageId: "ichinoen_1",
    },
    delivery: {
      deadLine: 12,
      day: 2,
      area: "13",
    },
  },
  {
    index: 3,
    name: "抹茶 お薄 宇治抹茶 初音200g 京都府産100% 製菓 粉末 パウダー 送料無料",
    description:
      "お菓子や料理、飲用の宇治抹茶です。<br>茶道用抹茶も製造する宇治抹茶専門メーカーが<br>極力品質を落とすことなく食品、飲料用に低価格を実現しました。<br>宇治茶の主産地　宇治田原よりお届けします。<br><br>和菓子店にも使用されている<br>菓子職人も認める宇治抹茶です。<br><br>お菓子や飲料、グリーンティーなどにご使用下さい。<br>※抹茶を点てるお客様は上級の宇治抹茶桐壷をお求め下さい。<br>※お買い得な業務用1kgもございます。<br>　このページ下に 商品ページがございます。<br><br>賞味期限は製造日より6カ月となっております。<br>これは風味高い状態で美味しくお召し上がりいただく期限として<br>抹茶メーカーが短く設定しているためです。<br><br>&lt;美味しいグリーティーの作り方&gt;<br><br>材料：抹茶：3g、グラニュー糖：14g、冷水：150ml、氷：適量<br><br>1）抹茶とグラニュー糖をグラスに入れよく混ぜる<br>2）適量の氷を入れる。<br><br>名称:抹茶（宇治抹茶100％）<br>原材料名:緑茶<br>販売者:(株)ティーエスケー<br>住所:京都府綴喜郡宇治田原町郷之口39-2<br>",
    headLine: "抹茶　粉末　製菓　パウダー　送料無料　抹茶ラテ",
    url: "https://store.shopping.yahoo.co.jp/tsk-store/302.html",
    inStock: true,
    code: "tsk-store_302",
    condition: "new",
    imageId: "tsk-store_302",
    image: {
      small: "https://item-shopping.c.yimg.jp/i/c/tsk-store_302",
      medium: "https://item-shopping.c.yimg.jp/i/g/tsk-store_302",
    },
    review: {
      count: 725,
      url: "https://shopping.yahoo.co.jp/review/item/list?store_id=tsk-store&page_key=302",
      rate: 4.66,
    },
    affiliateRate: 1,
    price: 1000,
    premiumPrice: 1000,
    premiumPriceStatus: false,
    premiumDiscountRate: null,
    premiumDiscountType: null,
    priceLabel: {
      taxable: true,
      defaultPrice: 1000,
      discountedPrice: null,
      fixedPrice: null,
      premiumPrice: null,
      periodStart: null,
      periodEnd: null,
    },
    point: {
      amount: 0,
      times: 0,
      bonusAmount: 9,
      bonusTimes: 1,
      premiumAmount: 0,
      premiumTimes: 0,
      premiumBonusAmount: 9,
      premiumBonusTimes: 1,
    },
    shipping: {
      code: 2,
      name: "送料無料",
    },
    genreCategory: {
      id: 17362,
      name: "抹茶",
      depth: 4,
    },
    parentGenreCategories: [
      {
        id: 2498,
        depth: 1,
        name: "食品",
      },
      {
        id: 2499,
        depth: 2,
        name: "ドリンク、水、お酒",
      },
      {
        id: 1399,
        depth: 3,
        name: "緑茶、日本茶",
      },
    ],
    brand: {
      id: null,
      name: "",
    },
    parentBrands: [],
    janCode: "4571163810202",
    payment: "16 64 512 1024 8192 1 128 256 4096 16384",
    releaseDate: null,
    seller: {
      sellerId: "tsk-store",
      name: "ティーエスケー",
      url: "https://store.shopping.yahoo.co.jp/tsk-store/",
      isBestSeller: false,
      review: {
        rate: 4.82,
        count: 731,
      },
      imageId: "tsk-store_1",
    },
    delivery: {
      deadLine: null,
      day: null,
      area: "",
    },
  },
  {
    index: 4,
    name: "抹茶 京都産 宇治抹茶 200g (100g×2) お薄 日本茶 緑茶 パウダー 粉末 送料無料",
    description:
      "名称：抹茶<br>内容量：200g(100g×2)<br>原材料名：緑茶(京都)<br>保存方法：直射日光・高温多湿の場所を避け、冷暗所にて保存して下さい。<br>配送区分：ゆうメール：全国送料無料　代金引換×　他商品一部同梱○ <br>宅配便：送料600円(税別)　代金引換○　他商品同梱○<br>(北海道・沖縄・離島除く)<br>製造者：株式会社高村園<br>広島県広島市安佐北区口田南1-25-27<br>TEL 082-845-8878<br><br>※原材料の緑茶の表示につきまして<br>抹茶の原料は碾茶ですが、碾茶の原料も緑茶となります。(煎茶やほうじ茶なども緑茶もしくは茶と表示)<br>この時、名称を抹茶とできるのは碾茶100%の場合です。本商品は碾茶100%から作られた抹茶となります。",
    headLine: "送料無料 お稽古用に お料理用に お菓子作りに",
    url: "https://store.shopping.yahoo.co.jp/ichinoen/kyoto-uji200.html",
    inStock: true,
    code: "ichinoen_kyoto-uji200",
    condition: "new",
    imageId: "ichinoen_kyoto-uji200",
    image: {
      small: "https://item-shopping.c.yimg.jp/i/c/ichinoen_kyoto-uji200",
      medium: "https://item-shopping.c.yimg.jp/i/g/ichinoen_kyoto-uji200",
    },
    review: {
      count: 418,
      url: "https://shopping.yahoo.co.jp/review/item/list?store_id=ichinoen&page_key=kyoto-uji200",
      rate: 4.58,
    },
    affiliateRate: 1,
    price: 1080,
    premiumPrice: 1080,
    premiumPriceStatus: false,
    premiumDiscountRate: null,
    premiumDiscountType: null,
    priceLabel: {
      taxable: true,
      defaultPrice: 1080,
      discountedPrice: null,
      fixedPrice: null,
      premiumPrice: null,
      periodStart: null,
      periodEnd: null,
    },
    point: {
      amount: 0,
      times: 0,
      bonusAmount: 10,
      bonusTimes: 1,
      premiumAmount: 0,
      premiumTimes: 0,
      premiumBonusAmount: 10,
      premiumBonusTimes: 1,
    },
    shipping: {
      code: 2,
      name: "送料無料",
    },
    genreCategory: {
      id: 17362,
      name: "抹茶",
      depth: 4,
    },
    parentGenreCategories: [
      {
        id: 2498,
        depth: 1,
        name: "食品",
      },
      {
        id: 2499,
        depth: 2,
        name: "ドリンク、水、お酒",
      },
      {
        id: 1399,
        depth: 3,
        name: "緑茶、日本茶",
      },
    ],
    brand: {
      id: null,
      name: "",
    },
    parentBrands: [],
    janCode: "",
    payment: "1024 8192 16 256 16384 4 512 128 2 8 64 4096 1",
    releaseDate: null,
    seller: {
      sellerId: "ichinoen",
      name: "一の縁",
      url: "https://store.shopping.yahoo.co.jp/ichinoen/",
      isBestSeller: false,
      review: {
        rate: 4.77,
        count: 1062,
      },
      imageId: "ichinoen_1",
    },
    delivery: {
      deadLine: 12,
      day: 2,
      area: "13",
    },
  },
  {
    index: 5,
    name: "抹茶 国内産抹茶 ２２０g 業務用 付属スプーンで約1100杯分 送料無料",
    description:
      "名称：抹茶<br>原材料：緑茶<br>産地：国内産<br>内容量：２２０ｇ<br>賞味期限：製造日より１０ヶ月<br><br>開封後はお早めにお召し上がりください。<br>高温多湿を避け移り香ににご注意ください。<br><br><br>【１〜２個ご注文の場合】☆ポスト投函（ネコポス便）☆<br><br>到着日時ご指定不可、代引き不可、送料無料<br><br><br>【３個以上ご注文の場合】☆ゆうパック☆<br><br>到着日時ご指定可、代引き可、送料無料",
    headLine: "抹茶 スイーツ作りに お点前練習用に最適 送料無料",
    url: "https://store.shopping.yahoo.co.jp/kakuto/machakokunai-m.html",
    inStock: true,
    code: "kakuto_machakokunai-m",
    condition: "new",
    imageId: "kakuto_machakokunai-m",
    image: {
      small: "https://item-shopping.c.yimg.jp/i/c/kakuto_machakokunai-m",
      medium: "https://item-shopping.c.yimg.jp/i/g/kakuto_machakokunai-m",
    },
    review: {
      count: 31,
      url: "https://shopping.yahoo.co.jp/review/item/list?store_id=kakuto&page_key=machakokunai-m",
      rate: 4.48,
    },
    affiliateRate: 1,
    price: 1200,
    premiumPrice: 1200,
    premiumPriceStatus: false,
    premiumDiscountRate: null,
    premiumDiscountType: null,
    priceLabel: {
      taxable: true,
      defaultPrice: 1200,
      discountedPrice: null,
      fixedPrice: null,
      premiumPrice: null,
      periodStart: null,
      periodEnd: null,
    },
    point: {
      amount: 0,
      times: 0,
      bonusAmount: 11,
      bonusTimes: 1,
      premiumAmount: 0,
      premiumTimes: 0,
      premiumBonusAmount: 11,
      premiumBonusTimes: 1,
    },
    shipping: {
      code: 2,
      name: "送料無料",
    },
    genreCategory: {
      id: 17362,
      name: "抹茶",
      depth: 4,
    },
    parentGenreCategories: [
      {
        id: 2498,
        depth: 1,
        name: "食品",
      },
      {
        id: 2499,
        depth: 2,
        name: "ドリンク、水、お酒",
      },
      {
        id: 1399,
        depth: 3,
        name: "緑茶、日本茶",
      },
    ],
    brand: {
      id: null,
      name: "",
    },
    parentBrands: [],
    janCode: "",
    payment: "4096 8192 16384 1 16 64 4",
    releaseDate: null,
    seller: {
      sellerId: "kakuto",
      name: "お茶のカクト",
      url: "https://store.shopping.yahoo.co.jp/kakuto/",
      isBestSeller: false,
      review: {
        rate: 4.66,
        count: 1366,
      },
      imageId: "kakuto_1",
    },
    delivery: {
      deadLine: null,
      day: null,
      area: "",
    },
  },
];

